version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10

    working_directory: /tmp/cypress-antd

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - /root/.cache/Cypress

      - run: npm run lint
      - run: npm test
      - run: npm run build
